spring:
    datasource:
        username: postgres
        password: DEVPG123!@#
        url: jdbc:postgresql://183.107.10.236:5432/devpg?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
    jpa:
        hibernate:
            ddl-auto: none
        show-sql: true
